In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 37s 3us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 5.8098789e-04, -6.6798657e-01,  5.3610981e-02,  1.0449912e-01,
         8.9190757e-01, -8.9721970e-02, -6.5381664e-01,  5.2026469e-01,
        -5.5382371e-01, -4.4319612e-01]], dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09573314, 0.0490577 , 0.1009469 , 0.10621685, 0.23343208,
        0.08746701, 0.04975779, 0.16097488, 0.05499047, 0.06142319]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.4364936

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2958 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1429 - accuracy: 0.9564
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1078 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0869 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0740 - accuracy: 0.9764


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0750 - accuracy: 0.9764 - 537ms/epoch - 2ms/step


[0.0749722346663475, 0.9764000177383423]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.57227937e-08, 2.05009432e-09, 3.67087318e-06, 3.78835903e-05,
        2.14201313e-11, 1.59933833e-07, 2.65057316e-11, 9.99920368e-01,
        8.20630646e-07, 3.71112292e-05],
       [1.41444934e-06, 4.69638944e-05, 9.99905348e-01, 2.93528974e-05,
        2.18007665e-12, 1.10419471e-07, 5.51724462e-08, 2.61451813e-14,
        1.68617553e-05, 7.08062428e-11],
       [2.29195578e-07, 9.99199688e-01, 2.33922910e-04, 1.28412075e-05,
        1.04611310e-04, 5.34866376e-06, 5.12504039e-06, 2.77455139e-04,
        1.55837857e-04, 4.93557536e-06],
       [9.99772966e-01, 2.76782997e-09, 5.90586797e-06, 4.79990199e-08,
        5.45554303e-06, 2.14480360e-06, 2.11865583e-04, 4.63322351e-07,
        8.09384382e-09, 1.15748060e-06],
       [2.57125225e-06, 9.69209490e-10, 3.91233243e-06, 6.56586607e-08,
        9.99083996e-01, 4.02238328e-07, 8.98095152e-07, 5.76700222e-06,
        8.61827687e-07, 9.01515305e-04]], dtype=float32)>